### ISSUE TITLE
NameError: undefined local variable or method `finished_env' for #<IndexTank::ClientResponseMiddleware:0x7fea9ffb1cd8>

### ISSUE THREAD

**Issue by vlado** [flaptor/indextank-rb#7]
I get this error from time to time and it last for 5-10mins and things get back to normal after that

NameError: undefined local variable or method `finished_env' for #IndexTank::ClientResponseMiddleware:0x7fea9ffb1cd8

Here is backtrace
https://gist.github.com/1506578

**Comment by santip** [comment]
This was a bug in the error handling of the API. It's simply hiding communication errors with the API, in this case caused by a short period of downtime.

The fix is here https://github.com/flaptor/indextank-rb/commit/3341bd238f6bfb1c1bb45bb4adf5f88dc3dd5ab5

It'll be included in the next gem release.

**Comment by vlado** [comment]
Thanks Santiago
